changes

diff --git a/bashscripts/configMover/moveConfigs b/bashscripts/configMover/moveConfigs
--- a/bashscripts/configMover/moveConfigs
+++ b/bashscripts/configMover/moveConfigs
@@ -69,40 +69,41 @@ then
 
 elif [ "$OPTION" = "12" ];
 then
-	sudo cp -R ~/.config/fish/ ~/linux-dotfiles/ && echo "Copied Fish Config to ~/linux-dotfiles/fish" || echo "failed to move config to linux-dotfiles";
-	sudo cp -R ~/.config/kitty/ ~/linux-dotfiles && echo "Copied Kitty Directory to ~/linux-dotfiles/kitty" || echo "failed to move Directory to linux-dotfiles";
-	sudo cp ~/.config/termite/config ~/linux-dotfiles/termite\ configs && echo "copied termite config to ~/linux-dotfiles/termite" || echo "failed to move config to linux-dotfiles";
-	sudo cp -R ~/.config/nvim ~/linux-dotfiles && echo "copied nvim Directory to linux-dotfiles" || echo "copied nvim Directory to linux-dotfiles"
-	sudo cp -R ~/.config/i3 ~/linux-dotfiles && echo "copied i3 Directory to linux-dotfiles" || echo "copied i3 Directory to linux-dotfiles"
-	sudo cp ~/.config/neofetch/config.conf ~/linux-dotfiles/neofetch && echo "Copied neofetch config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
-	sudo cp ~/.config/zathura/zathurarc ~/linux-dotfiles/zathura && echo "Copied zathura config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
-	sudo cp -R ~/.config/picom ~/linux-dotfiles && echo "Copied picom config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
-	sudo cp ~/.config/alacritty/alacritty.yml ~/linux-dotfiles/alacritty && echo "Copied alacritty config to ~/linux-dotfiles/alacritty" || echo "failed to move config to linux-dotfiles";
+	sudo cp -R ~/.config/fish/ ~/linux-dotfiles/.config/ && echo "Copied Fish Config to ~/linux-dotfiles/fish" || echo "failed to move config to linux-dotfiles";
+	sudo cp -R ~/.config/kitty/ ~/linux-dotfiles/.config/ && echo "Copied Kitty Directory to ~/linux-dotfiles/kitty" || echo "failed to move Directory to linux-dotfiles";
+	sudo cp ~/.config/termite/config ~/linux-dotfiles/.config/termite\ configs && echo "copied termite config to ~/linux-dotfiles/termite" || echo "failed to move config to linux-dotfiles";
+	sudo cp -R ~/.config/nvim ~/linux-dotfiles/.config/ && echo "copied nvim Directory to linux-dotfiles" || echo "copied nvim Directory to linux-dotfiles"
+	sudo cp -R ~/.config/i3 ~/linux-dotfiles/.config/ && echo "copied i3 Directory to linux-dotfiles" || echo "copied i3 Directory to linux-dotfiles"
+	sudo cp ~/.config/neofetch/config.conf ~/linux-dotfiles/.config/neofetch && echo "Copied neofetch config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
+	sudo cp ~/.config/zathura/zathurarc ~/linux-dotfiles/.config/zathura && echo "Copied zathura config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
+	sudo cp -R ~/.config/picom ~/linux-dotfiles/.config/ && echo "Copied picom config to ~/linux-dotfiles" || echo "failed to move config to linux-dotfiles";
+	sudo cp ~/.config/alacritty/alacritty.yml ~/linux-dotfiles/.config/alacritty && echo "Copied alacritty config to ~/linux-dotfiles/alacritty" || echo "failed to move config to linux-dotfiles";
 	sudo cp -R ~/backgrounds ~/linux-dotfiles && echo "Moved Backgrounds Directory To ~/linux-dotfiles/Backgrounds" || echo "Failed to move Backgrounds Directory To ~/linux-dotfiles/Backgrounds"
-	sudo cp /usr/bin/moveConfigs ~/linux-dotfiles/configMover && echo "Moved config mover to ~/linux-dotfiles/configMover" || echo "failed to move configmove to ~/linux-dotfiles/configMover"
-	sudo cp /usr/bin/pall ~/linux-dotfiles/pall && echo "Moved push-all tool to ~/linux-dotfiles/pall" || echo "Failed to move push-all tool to ~/linux-dotfiles/pall"
-	sudo cp /usr/bin/i3changer ~/linux-dotfiles/i3ConfigChanger && echo "Moved i3 config changer tool to ~/linux-dotfiles/i3ConfigChanger" || echo "Failed to move i3 config changer tool to ~/linux-dotfiles/i3ConfigChanger "
-	sudo cp -R ~/.config/rofi ~/linux-dotfiles && echo "moved rofi configs to linux-dotfiles" || echo "Failed to move rofi configs to linux dotfiles"
-	sudo cp -R ~/.config/rofibackups ~/linux-dotfiles
-	sudo cp -R ~/.config/qutebrowser ~/linux-dotfiles && echo "moved qutebrowser configs to linux-dotfiles" || echo "failed to move qutebrowser configs to linux-dotfiles"
+	sudo cp /usr/bin/moveConfigs ~/linux-dotfiles/bashscripts/configMover && echo "Moved config mover to ~/linux-dotfiles/configMover" || echo "failed to move configmove to ~/linux-dotfiles/configMover"
+	sudo cp /usr/bin/pall ~/linux-dotfiles/bashscripts/ && echo "Moved push-all tool to ~/linux-dotfiles/pall" || echo "Failed to move push-all tool to ~/linux-dotfiles/pall"
+	sudo cp /usr/bin/i3changer ~/linux-dotfiles/bashscripts/i3ConfigChanger && echo "Moved i3 config changer tool to ~/linux-dotfiles/i3ConfigChanger" || echo "Failed to move i3 config changer tool to ~/linux-dotfiles/i3ConfigChanger "
+	sudo cp -R ~/.config/rofi ~/linux-dotfiles/.config/ && echo "moved rofi configs to linux-dotfiles" || echo "Failed to move rofi configs to linux dotfiles"
+	sudo cp -R ~/.config/rofibackups ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/qutebrowser ~/linux-dotfiles/.config/ && echo "moved qutebrowser configs to linux-dotfiles" || echo "failed to move qutebrowser configs to linux-dotfiles"
 	sudo cp ~/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.10/site-packages/pycodestyle.py ~/linux-dotfiles/pycodestyle && echo "moved pycodestyle to linex-dotfiles" || echo "failed to move pycodestyle to linux-dotfiles"
 	sudo cp ~/.local/share/nvim/mason/packages/python-lsp-server/venv/lib/python3.10/site-packages/pyflakes/messages.py ~/linux-dotfiles/pyflakes && echo "moved pyflakes messages.py to linux-dotfiles" || echo "failed to move pyflakes messages.py to linux-dotfiles"
-	sudo cp -R ~/.config/tint2 ~/linux-dotfiles && echo "Moved tint2 Directory to linux-dotfiles" || echo "Failed to move configs to linux-dotfiles"
-	sudo cp -R ~/.config/polybar ~/linux-dotfiles && echo "Copied polybar Directory to linux-dotfiles" || echo "Copied polybar Directory to linux-dotfiles"
-	sudo cp -R ~/.config/inkscape-figures ~/linux-dotfiles
-	sudo cp -R ~/Pictures/Grids ~/linux-dotfiles
+	sudo cp -R ~/.config/tint2 ~/linux-dotfiles/.config/ && echo "Moved tint2 Directory to linux-dotfiles" || echo "Failed to move configs to linux-dotfiles"
+	sudo cp -R ~/.config/polybar ~/linux-dotfiles/.config/ && echo "Copied polybar Directory to linux-dotfiles" || echo "Copied polybar Directory to linux-dotfiles"
+	sudo cp -R ~/.config/inkscape-figures ~/linux-dotfiles/.config
+	sudo cp -R ~/Pictures/Grids ~/linux-dotfiles/Pictures
+	sudo cp -R ~/Pictures/Graphs ~/linux-dotfiles/Pictures
 	sudo cp -R ~/dev/latex/template/preamble.tex ~/linux-dotfiles/latex
 	sudo cp -R ~/dev/latex/template/macros.tex ~/linux-dotfiles/latex
-	sudo cp ~/.tmux.conf ~/linux-dotfiles/tmux
-	sudo cp -R ~/.config/hypr ~/linux-dotfiles
-	sudo cp -R ~/.config/HyprV ~/linux-dotfiles
-	sudo cp -R ~/.config/waybar ~/linux-dotfiles
-	sudo cp -R ~/.config/cava ~/linux-dotfiles
-	sudo cp -R ~/.config/wofi ~/linux-dotfiles
-	sudo cp -R ~/.config/eww ~/linux-dotfiles
-	sudo cp -R ~/.config/spotify ~/linux-dotfiles
-	sudo cp -R ~/.config/spicetify ~/linux-dotfiles
-	sudo cp -R ~/.config/vis ~/linux-dotfiles
+	sudo cp ~/.tmux.conf ~/linux-dotfiles/.config/tmux
+	sudo cp -R ~/.config/hypr ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/HyprV ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/waybar ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/cava ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/wofi ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/eww ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/spotify ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/spicetify ~/linux-dotfiles/.config/
+	sudo cp -R ~/.config/vis ~/linux-dotfiles/.config/
 
 else
 	echo "Invalid Option"
